packages:
  - '.'

overrides:
  '@babel/runtime': '>=7.26.10'
  '@pnpm/npm-conf': '>=3.0.2'
  brace-expansion: '>=5.0.5'
  cross-spawn: '>=7.0.5'
  flatted: '>=3.4.2'
  follow-redirects: '>=1.16.0'
  minimatch: '>=10.2.4'
  picomatch@<2.3.2: 4.0.4
  picomatch@>=3 <3.0.2: 4.0.4
  picomatch@>=4 <4.0.4: 4.0.4
  postcss: '>=8.5.10'
  rollup: '>=4.59.0'
  tar: 7.5.13
  undici: '>=6.24.0'

allowBuilds:
  '@swc/core': true
  cypress: true
  esbuild: true
  msw: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
