name: HTML Validator

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  html-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"

      - name: Setup pnpm
        uses: pnpm/action-setup@f2b2b233b538f500472c7274c7012f57857d8ce0
        with:
          version: 10
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install wait-on
        run: |
          pnpm add -D wait-on

      - name: Build Next.js app
        run: pnpm build

      - name: Start Next.js app
        run: pnpm start &

      - name: Wait for the application to be ready
        run: pnpm exec wait-on http://localhost:3000

      - name: Download HTML pages for validation
        run: |
          # Create directory for downloaded HTML files
          mkdir -p html-pages
          
          # Download HTML pages from the running server
          echo "Downloading home page..."
          curl -s http://localhost:3000 > html-pages/index.html
          
          echo "Downloading CV page..."
          curl -s http://localhost:3000/cv > html-pages/cv.html
          
          echo "Downloading Prosjekter page..."
          curl -s http://localhost:3000/prosjekter > html-pages/prosjekter.html
          
          echo "Downloading Kontakt page..."
          curl -s http://localhost:3000/kontakt > html-pages/kontakt.html
          
          # Verify files were created
          ls -la html-pages/

      - name: Validate HTML files
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: html-pages/
          css: true

      - name: Upload HTML validation log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-validation-log
          path: log.log

      - name: Stop server
        if: always()
        run: |
          pkill -f "next start" || true